console_title_template = '{{ .Shell }} in {{ .Folder }}'
version = 3
final_space = true

[palette]
  black = '#141B1E'
  blue = '#67B0E8'
  darkgray = '#232A2D'
  gray = '#B3B9B8'
  green = '#8CCF7E'
  lightblue = '#6CBFBF'
  red = '#E57474'
  violet = '#C47FD5'
  white = '#DADADA'
  yellow = '#E5C76B'

[transient_prompt]
  template = '󰅂 '
  foreground = 'p:lightblue'
  background = 'transparent'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    leading_diamond = ''
    trailing_diamond = ''
    template = ' {{ .Path }}'
    foreground = 'p:blue'
    background = 'p:darkgray'
    type = 'path'
    style = 'diamond'

    [blocks.segments.properties]
      cache_duration = 'none'
      home_icon = '󰟒'
      style = 'folder'

      [blocks.segments.properties.mapped_locations]
        '/home/killar/Desktop/' = '󰇄'
        '/home/killar/Music' = '󱍙'
        '/home/killar/Pictures/' = '󰉏'
        '/home/killar/Videos' = '󱧺'
        '/home/killar/projects/' = '󱧼'

  [[blocks.segments]]
    leading_diamond = ''
    trailing_diamond = ''
    template = '  {{ .Full }} '
    foreground = 'p:red'
    background = 'p:darkgray'
    type = 'rust'
    style = 'diamond'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    leading_diamond = ''
    trailing_diamond = ''
    template = '  {{ .Full }}'
    foreground = 'p:red'
    background = 'p:darkgray'
    type = 'java'
    style = 'diamond'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    leading_diamond = ''
    trailing_diamond = ''
    template = '{{ .UpstreamIcon }}{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }}{{ if gt .StashCount 0 }}  {{ .StashCount }}{{ end }}'
    foreground = 'p:yellow'
    background = 'p:darkgray'
    type = 'git'
    style = 'diamond'

    [blocks.segments.properties]
      cache_duration = 'none'
      fetch_status = true
      fetch_upstream_icon = true

[[blocks]]
  type = 'prompt'
  alignment = 'right'

  [[blocks.segments]]
    leading_diamond = ''
    template = '󱦟 {{ .FormattedMs }}'
    foreground = 'p:yellow'
    background = 'p:darkgray'
    type = 'executiontime'
    style = 'diamond'

    [blocks.segments.properties]
      cache_duration = 'none'
      style = 'round'
      threshold = 5000

  [[blocks.segments]]
    trailing_diamond = ''
    template = '<p:black></> {{ if .Error}} {{ .Code }}{{ else }}{{ end }}'
    foreground = 'p:white'
    background = 'p:green'
    type = 'status'
    style = 'diamond'
    background_templates = ['{{ if .Error }}p:red{{ end }}']

    [blocks.segments.properties]
      always_enabled = true
      cache_duration = 'none'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    template = ' 󰅂'
    foreground = 'p:violet'
    background = 'transparent'
    type = 'text'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'
